SELECT
    *
FROM
    CO.CUSTOMERS;

SELECT
    *
FROM
    CO.ORDERS;

SELECT
    *
FROM
    CO.CUSTOMERS
WHERE
    FULL_NAME LIKE '%M';

SELECT
    COC.CUSTOMER_ID,
    COC.FULL_NAME,
    COUNT(COO.ORDER_ID) AS ORDER_COUNT
FROM
         CO.CUSTOMERS COC
    JOIN CO.ORDERS COO ON COC.CUSTOMER_ID = COO.CUSTOMER_ID
GROUP BY
    COC.CUSTOMER_ID,
    COC.FULL_NAME
ORDER BY
    3 DESC;

SELECT
    OI.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM
         CO.ORDER_ITEMS OI
    JOIN CO.PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    OI.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY
    TOTAL_REVENUE DESC;

SELECT
    PRODUCT_NAME,
    UNIT_PRICE
FROM
    CO.PRODUCTS
WHERE
    UNIT_PRICE > (SELECT
            AVG(UNIT_PRICE)
        FROM
            CO.PRODUCTS);